[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.17.0"
  NODE_OPTIONS = "--max_old_space_size=4096"
  GENERATE_SOURCEMAP = "false"
  REACT_APP_BACKEND_URL = "https://your-app-name.herokuapp.com"
  REACT_APP_MONGODB_ATLAS_URI = "mongodb+srv://tonnelque:cdcdcdcd@cluster0.mgg7dgs.mongodb.net/tgmarket?retryWrites=true&w=majority"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Переменные окружения для продакшена
[context.production.environment]
  REACT_APP_BACKEND_URL = "https://your-app-name.herokuapp.com"
  REACT_APP_MONGODB_ATLAS_URI = "mongodb+srv://tonnelque:cdcdcdcd@cluster0.mgg7dgs.mongodb.net/tgmarket?retryWrites=true&w=majority" 